config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "restaurants#index"
  resources :restaurants do
    resources :reviews, only: [ :index, :new, :create ]
  end
  resources :reviews, only: [ :show, :edit, :update, :destroy ]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :reviews, dependent: :destroy
  validates :name, presence: true
  validates :address, presence: true
  validates :category, inclusion: { in: ["chinese", "italian", "japanese", "french", "belgian"] }
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant
  validates :content, presence: true
  validates :rating, inclusion: { in: [0, 1, 2, 3, 4, 5] }, numericality: { only_integer: true }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController

  before_action :set_restaurant, only: [:show, :edit, :update, :destroy]

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    return redirect_to restaurant_path(@restaurant) if @restaurant.save
    render :new
  end

  def index
    @restaurants = Restaurant.all
  end
  def show
  end

  def edit
  end
  def update
    if @restaurant.update(restaurant_params)
      redirect_to restaurant_path(@restaurant)
    else
      render :edit
    end
  end
  def destroy
    @restaurant.destroy
    redirect_to restaurants_path
  end

  private

  def set_restaurant
    @restaurant = Restaurant.find(params[:id])
  end

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :category, :phone_number)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_restaurant, only: [:new, :create, :show, :edit, :update, :destroy]

  def new
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    @review.restaurant_id = @restaurant.id
    return redirect_to restaurant_path(@restaurant) if @review.save
    render :new
  end

  def index
    @reviews = Review.all

  end

  def show

  end
  private

  def set_restaurant
    @restaurant = Restaurant.find(params[:restaurant_id])
  end

  def review_params
    params.require(:review).permit(:content, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RailsYelpMvp</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
  <%= yield %>
</body>
</html>

app/views/restaurants/_form.html.erb
<%= simple_form_for(restaurant) do |f| %>
<%= f.error_notification %>
<div class="form-group">
  <%= f.input :name, class: 'form-control' %>
</div>

<div class="form-group">
  <%= f.input :address, class: 'form-control' %>
</div>

<div class="form-group">
  <%= f.input :category, class: 'form-control' %>
</div>

<div class="form-group">
  <%= f.input :phone_number, class: 'form-control' %>
</div>

<%= f.submit class: 'btn btn-primary' %>
<% end %>

app/views/restaurants/edit.html.erb
<%= render 'form', restaurant: @restaurant %>

app/views/restaurants/index.html.erb
<h1>All restaurants</h1>
<br>
<br>
<% @restaurants.each do |restaurant| %>
  <p><%= link_to restaurant.name, restaurant_path(restaurant) %></p>
  <% end %>
<br>
<br>

<%= link_to "Add a new restaurant", new_restaurant_path %>

app/views/restaurants/new.html.erb
<%= render 'form', restaurant: @restaurant %>

app/views/restaurants/show.html.erb
<h1><%= @restaurant.name  %></h1>

<h2>Address: <%= @restaurant.address %></h2>
<h2>Category: <%= @restaurant.category %></h2>
<h2>Phone number: <%= @restaurant.phone_number %></h2>

<br>
<br>

<%= link_to "Delete this restaurant", restaurant_path(@restaurant),
  method: :delete,
  data: { confirm: "Are you sure?" } %>
<%= link_to "Edit this restaurant", edit_restaurant_path %>

<p><%= link_to "Go back", restaurants_path %></p>

<h2>Reviews:</h2>
<p><%= link_to "Write a new review", new_restaurant_review_path(@restaurant) %></p>
<!-- <p><%#= link_to "Edit a review", edit_review_path(@review) %></p> -->

app/views/reviews/_form.html.erb
<%= simple_form_for [restaurant, review] do |f| %>
<%= f.error_notification %>

<div class="form-group">
  <%= f.input :content, class: 'form-control' %>
</div>

<div class="form-group">
  <%= f.input :rating, class: 'form-control' %>
</div>

<%= f.submit class: 'btn btn-primary' %>
<% end %>

app/views/reviews/new.html.erb
<%= render 'form', review: @review, restaurant: @restaurant %>